### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by AstraxCZ** [Konsl/spicetify-ncs-visualizer#1]
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/88210947/131002e6-7148-4eeb-a2f0-2198d69e5219)

**Comment by SpaceEnergy** [comment]
the same for me

**Comment by Konsl** [comment]
Please make sure that you extracted the downloaded zip file and that the CustomApps/ncs-visualizer folder contains index.js, manifest.json, and style.css, not a subfolder with those files. I don't know if the documentation is clear enough about that part. Let me know if it works.

**Comment by Konsl** [comment]
Closing this ticket based on the comment above. Feel free to reopen if the problem still exists.

**Comment by AstraxCZ** [comment]
still dont work

![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/88210947/002e887a-59f7-461f-b800-92ed10989237)

![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/88210947/a9b0e2d9-1b9e-4397-a553-7cbefcf1f98c)
