### ISSUE TITLE
There is no Index.js??

### ISSUE THREAD

**Issue by NoahBidgood** [Konsl/spicetify-ncs-visualizer#13]
Sorry I am very new and have no idea whatsoever what im doing, but I got an error, there is no Index.js file and I cannot find it. Thanks.

**Comment by Konsl** [comment]
This is usually a configuration error, maybe a spelling mistake in the file / directory name? Otherwise try looking at #1

**Comment by NoahBidgood** [comment]
Ive double checked everything, and checked the repo, theres no index.js file, and i cant find it anywhere.

**Comment by NoahBidgood** [comment]
Never mind i am just very stupid.
