### ISSUE TITLE
Visualizer doesn't work at all all of a sudden

### ISSUE THREAD

**Issue by grejprrik** [Konsl/spicetify-ncs-visualizer#19]
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/160502398/77bad583-3412-4782-9412-0086ea5e9aee)
doesnt work, instead shows this error message.

**Comment by anurag-chemakurthi** [comment]
Reinstalled it today and also getting the same message

**Comment by AegeanExe** [comment]
Same issue.

**Comment by IsaiahTGP** [comment]
same here

**Comment by pragit-raj-sharma** [comment]
same

**Comment by GGshor** [comment]
I've fixed the issue in https://github.com/Konsl/spicetify-ncs-visualizer/pull/20, just waiting for the PR to be accepted or for @Konsl to fix it.

**Comment by Tr3yWay996** [comment]
it doesnt even show lol
