### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by AxaliaN** [Konsl/spicetify-ncs-visualizer#2]
Hiya,

I installed the app but all I see is this: 
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/724353/e84d5634-f525-490f-aff0-34fd5b5cb67d)

I'm on Ubuntu. Any ideas?

**Comment by Konsl** [comment]
This message indicates that there was an error while loading the audio analysis data for the currently playing track, which the visualizer needs.

The reason could be a networking issue or an unsupported type of track, as only songs are supported, whereas podcast episodes are not. I've also noticed that certain songs don't have the analysis data, which means they won't work with my visualizer.

Could you try it on a different song and let me know if it works?
Thank you

**Comment by AxaliaN** [comment]
Yep, works! Thanks for the quick answer!
