### ISSUE TITLE
Empty page with Comfy theme

### ISSUE THREAD

**Issue by xhuriken** [Konsl/spicetify-ncs-visualizer#24]
NCS Visualizer work well, but with 'Comfy' theme the Visualizer page is empty.
It work with other theme, and the 'Comfy (Legacy)' theme.
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/73635763/083144e5-12ff-4af5-ac12-48a882dc17eb)

**Comment by Konsl** [comment]
Use this snippet
https://github.com/Konsl/spicetify-ncs-visualizer/issues/21#issuecomment-2050515422

There is also a link to this at the bottom of the README.
If you could think of a better place to put this, so more people would notice, let me know.
