### ISSUE TITLE
Not working on Comfy Theme

### ISSUE THREAD

**Issue by AxaliaN** [Konsl/spicetify-ncs-visualizer#3]
Hiya,

yesterday I installed a new theme in Spicetify and noticed this app isn't working in it. I also mentioned this on their repo (https://github.com/Comfy-Themes/Spicetify/) but it might be interesting for you as well, or it might even be a bug in this app. Could you take a look?

Thanks!

**Comment by Konsl** [comment]
Thanks for letting me know. Should be fixed.
Please look at the [README](README.md) for update instructions.
Feel free to reopen if you need help.

**Comment by AxaliaN** [comment]
You're the best, it works!
