### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Cryptic1526** [Konsl/spicetify-ncs-visualizer#6]
I installed it, how do I enable it? Theres no button or anything as far as I can see, no errors in installation as well.

**Comment by Cryptic1526** [comment]
@Konsl

**Comment by Konsl** [comment]
You should see "NCS Visualizer" in the sidebar. Just click on it to see the Visualizer. Hope this is helpful.

**Comment by Cryptic1526** [comment]
Oh I'm using a custom theme. Do I have to disable it? 

I'm using Galaxy: ![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/119151348/982a5851-5b1c-495a-9f0f-aec0d7ec548e)

Nothing is on the right sidebar.

**Comment by Konsl** [comment]
A theme should not be the problem in this case (other sidebar entries are also visible).
It is possible that the visualizer is not installed correctly.

Is 'ncs-visualizer' listed in the custom apps list of the version info dialog?
(App Menu ⇾ Help ⇾ About Spotify ⇾ expand "Spicetify")

**Comment by Cryptic1526** [comment]
Oh yeah, it doesn't come up in the list. 
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/119151348/403caf70-7fce-48a6-a506-80c7a81861c5)

I'll reinstall it and see if that works.

EDIT: It worked now for some reason, I think I missed a step the first time. Also, the visualizer's really laggy, is there a way to fix that?

**Comment by Konsl** [comment]
Other people seem to have problems with performance as well (see #4), I am still working on a solution.

**Comment by Cryptic1526** [comment]
Oh alr, I'll follow that thread then. Thanks for your help!
